export default {
    INITIALIZE_GAMES_INFO: 'INITIALIZE_GAMES_INFO',
    INITIALIZE_GAME_INFO: 'INITIALIZE_GAME_INFO',
    INITIALIZE_GAME_LEVEL: 'INITIALIZE_GAME_LEVEL',
    UPDATE_GAME_LEVEL: 'UPDATE_GAME_LEVEL'
};
