export default {
    INITIALIZE_WORD_PAIRS: 'INITIALIZE_WORD_PAIRS',
    UPDATE_WORD_PAIRS_AFTER_DELETION: 'UPDATE_WORD_PAIRS_AFTER_DELETION',
    UPDATE_WORD_PAIRS_AFTER_ADDITION: 'UPDATE_WORD_PAIRS_AFTER_ADDITION',
    UPDATE_WORD_PAIRS_AFTER_EDITING: 'UPDATE_WORD_PAIRS_AFTER_EDITING'
};
