package ru.inwords.inwords.game.presentation.listening

const val LISTENING_LEVEL_RESULT_WORD_CHOSEN_KEY = "LISTENING_LEVEL_RESULT_WORD_CHOSEN_KEY"
const val LISTENING_LEVEL_RESULT_TTS_CLICKED_KEY = "LISTENING_LEVEL_RESULT_TTS_CLICKED_KEY"
const val USERS_CHOICE_KEY = "USERS_CHOICE_KEY"
const val WORD_MODEL_KEY = "WORD_MODEL_KEY"
