export default {
    DATA_TRANSFER_BEGIN: 'DATA_TRANSFER_BEGIN',
    DATA_TRANSFER_END: 'DATA_TRANSFER_END',

    ERROR_MESSAGE_SETTING: 'ERROR_MESSAGE_SETTING',
    ERROR_MESSAGE_RESET: 'ERROR_MESSAGE_RESET'
};
