export const BEGIN_LOADING = 'BEGIN_LOADING';
export const END_LOADING = 'END_LOADING';

export const SET_SNACKBAR_MESSAGE = 'SET_SNACKBAR_MESSAGE';
export const RESET_SNACKBAR_MESSAGE = 'RESET_SNACKBAR_MESSAGE';
