const gameConstants = {
    GAMES_INFO_INITIALIZATION: 'GAMES_INFO_INITIALIZATION',

    GAME_INFO_INITIALIZATION: 'GAME_INFO_INITIALIZATION',
    GAME_INFO_CLEARING: 'GAME_INFO_CLEARING',
    
    GAME_LEVEL_INITIALIZATION: 'GAME_LEVEL_INITIALIZATION',
    GAME_LEVEL_UPDATE: 'GAME_LEVEL_UPDATE',
    GAME_LEVEL_CLEARING: 'GAME_LEVEL_CLEARING'
};

export default gameConstants;
