const gameConstants = {
    GAMES_INFO_INITIALIZATION: 'GAMES_INFO_INITIALIZATION',
    GAMES_INFO_UPDATE_AFTER_ADDITION: 'GAMES_INFO_UPDATE_AFTER_ADDITION',
    GAMES_INFO_UPDATE_AFTER_DELETION: 'GAMES_INFO_UPDATE_AFTER_DELETION',

    GAME_INFO_INITIALIZATION: 'GAME_INFO_INITIALIZATION',
    GAME_INFO_CLEARING: 'GAME_INFO_CLEARING',
    
    GAME_LEVEL_INITIALIZATION: 'GAME_LEVEL_INITIALIZATION',
    GAME_LEVEL_CLEARING: 'GAME_LEVEL_CLEARING'
};

export default gameConstants;
