export const INITIALIZE_GAMES_INFO = 'INITIALIZE_GAMES_INFO';
export const INITIALIZE_GAME_INFO = 'INITIALIZE_GAME_INFO';
export const INITIALIZE_GAME_LEVEL = 'INITIALIZE_GAME_LEVEL';
export const UPDATE_GAME_INFO = 'UPDATE_GAME_INFO';
