export const gameConstants = {
    GAMES_INFO_RECEIVED: 'GAMES_INFO_RECEIVED',

    GAME_INFO_RECEIVED: 'GAME_INFO_RECEIVED',
    GAME_INFO_RESET: 'GAME_INFO_RESET',

    GAME_LEVEL_RECEIVED: 'GAME_LEVEL_RECEIVED',
    GAME_LEVEL_RESET: 'GAME_LEVEL_RESET'
};
