const userConstants = {
    REDIRECT: 'REDIRECT',
    REDIRECTED: 'REDIRECTED',

    USER_INFO_INITIALIZATION: 'USER_INFO_INITIALIZATION',
    USER_INFO_UPDATE: 'USER_INFO_UPDATE',
};

export default userConstants;
