export const userConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_REDIRECTED: 'LOGIN_REDIRECTED',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_REDIRECTED: 'REGISTER_REDIRECTED',
    REGISTER_FAILURE: 'REGISTER_FAILURE'
};
