export const wordlistConstants = {
    PAIRS_PULL_REQUEST: 'PAIRS_PULL_REQUEST',
    PAIRS_PULL_SUCCESS: 'PAIRS_PULL_SUCCESS',
    PAIRS_PULL_FAILURE: 'PAIRS_PULL_FAILURE',

    PAIRS_DEL_REQUEST: 'PAIRS_DEL_REQUEST',
    PAIRS_DEL_SUCCESS: 'PAIRS_DEL_SUCCESS',
    PAIRS_DEL_FAILURE: 'PAIRS_DEL_FAILURE',

    PAIRS_ADD_REQUEST: 'PAIRS_ADD_REQUEST',
    PAIRS_ADD_SUCCESS: 'PAIRS_ADD_SUCCESS',
    PAIRS_ADD_FAILURE: 'PAIRS_ADD_FAILURE',

    PAIRS_PULL_LOCAL_REFRESH: 'PAIRS_PULL_LOCAL_REFRESH',
    PAIRS_DEL_LOCAL_REFRESH: 'PAIRS_DEL_LOCAL_REFRESH',
    PAIRS_ADD_LOCAL_REFRESH: 'PAIRS_ADD_LOCAL_REFRESH'
};
