export const INITIALIZE_WORD_PAIRS = 'INITIALIZE_WORD_PAIRS';
export const UPDATE_WORD_PAIRS_AFTER_DELETION = 'UPDATE_WORD_PAIRS_AFTER_DELETION';
export const UPDATE_WORD_PAIRS_AFTER_ADDITION = 'UPDATE_WORD_PAIRS_AFTER_ADDITION';
export const UPDATE_WORD_PAIRS_AFTER_EDITING = 'UPDATE_WORD_PAIRS_AFTER_EDITING';
