export const wordlistConstants = {
    PAIRS_PULL_LOCAL_REFRESH: 'PAIRS_PULL_LOCAL_REFRESH',
    PAIRS_DEL_LOCAL_REFRESH: 'PAIRS_DEL_LOCAL_REFRESH',
    PAIRS_ADD_LOCAL_REFRESH: 'PAIRS_ADD_LOCAL_REFRESH',
    PAIRS_EDIT_LOCAL_REFRESH: 'PAIRS_EDIT_LOCAL_REFRESH',
    PAIRS_CHECK_UPDATE: 'PAIRS_CHECK_UPDATE'
};
