export const wordlistConstants = {
    PULL_PAIRS_REQUEST: 'PULL_PAIRS_REQUEST',
    PULL_PAIRS_SUCCESS: 'PULL_PAIRS_SUCCESS',
    PULL_PAIRS_FAILURE: 'PULL_PAIRS_FAILURE',

    DEL_PAIRS_REQUEST: 'DEL_PAIRS_REQUEST',
    DEL_PAIRS_SUCCESS: 'DEL_PAIRS_SUCCESS',
    DEL_PAIRS_FAILURE: 'DEL_PAIRS_FAILURE',

    PAIRS_RELEVANT: 'PAIRS_RELEVANT',
    PAIRS_IRRELEVANT: 'PAIRS_IRRELEVANT'
};
