// source: WordSet.v2.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Dictionary_v2_pb = require('./Dictionary.v2_pb.js');
goog.object.extend(proto, Dictionary_v2_pb);
goog.exportSymbol('proto.WordSet.v2.WordSetWord', null, global);
goog.exportSymbol('proto.WordSet.v2.WordSetWordsReply', null, global);
goog.exportSymbol('proto.WordSet.v2.WordSetWordsRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WordSet.v2.WordSetWordsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.WordSet.v2.WordSetWordsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WordSet.v2.WordSetWordsRequest.displayName = 'proto.WordSet.v2.WordSetWordsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WordSet.v2.WordSetWordsReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.WordSet.v2.WordSetWordsReply.repeatedFields_, null);
};
goog.inherits(proto.WordSet.v2.WordSetWordsReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WordSet.v2.WordSetWordsReply.displayName = 'proto.WordSet.v2.WordSetWordsReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WordSet.v2.WordSetWord = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.WordSet.v2.WordSetWord, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WordSet.v2.WordSetWord.displayName = 'proto.WordSet.v2.WordSetWord';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WordSet.v2.WordSetWordsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.WordSet.v2.WordSetWordsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WordSet.v2.WordSetWordsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WordSet.v2.WordSetWordsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    wordsetid: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WordSet.v2.WordSetWordsRequest}
 */
proto.WordSet.v2.WordSetWordsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WordSet.v2.WordSetWordsRequest;
  return proto.WordSet.v2.WordSetWordsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WordSet.v2.WordSetWordsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WordSet.v2.WordSetWordsRequest}
 */
proto.WordSet.v2.WordSetWordsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWordsetid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WordSet.v2.WordSetWordsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WordSet.v2.WordSetWordsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WordSet.v2.WordSetWordsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WordSet.v2.WordSetWordsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWordsetid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 WordSetId = 1;
 * @return {number}
 */
proto.WordSet.v2.WordSetWordsRequest.prototype.getWordsetid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.WordSet.v2.WordSetWordsRequest} returns this
 */
proto.WordSet.v2.WordSetWordsRequest.prototype.setWordsetid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.WordSet.v2.WordSetWordsReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WordSet.v2.WordSetWordsReply.prototype.toObject = function(opt_includeInstance) {
  return proto.WordSet.v2.WordSetWordsReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WordSet.v2.WordSetWordsReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WordSet.v2.WordSetWordsReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    wordsList: jspb.Message.toObjectList(msg.getWordsList(),
    proto.WordSet.v2.WordSetWord.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WordSet.v2.WordSetWordsReply}
 */
proto.WordSet.v2.WordSetWordsReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WordSet.v2.WordSetWordsReply;
  return proto.WordSet.v2.WordSetWordsReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WordSet.v2.WordSetWordsReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WordSet.v2.WordSetWordsReply}
 */
proto.WordSet.v2.WordSetWordsReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.WordSet.v2.WordSetWord;
      reader.readMessage(value,proto.WordSet.v2.WordSetWord.deserializeBinaryFromReader);
      msg.addWords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WordSet.v2.WordSetWordsReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WordSet.v2.WordSetWordsReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WordSet.v2.WordSetWordsReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WordSet.v2.WordSetWordsReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.WordSet.v2.WordSetWord.serializeBinaryToWriter
    );
  }
};


/**
 * repeated WordSetWord Words = 1;
 * @return {!Array<!proto.WordSet.v2.WordSetWord>}
 */
proto.WordSet.v2.WordSetWordsReply.prototype.getWordsList = function() {
  return /** @type{!Array<!proto.WordSet.v2.WordSetWord>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.WordSet.v2.WordSetWord, 1));
};


/**
 * @param {!Array<!proto.WordSet.v2.WordSetWord>} value
 * @return {!proto.WordSet.v2.WordSetWordsReply} returns this
*/
proto.WordSet.v2.WordSetWordsReply.prototype.setWordsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.WordSet.v2.WordSetWord=} opt_value
 * @param {number=} opt_index
 * @return {!proto.WordSet.v2.WordSetWord}
 */
proto.WordSet.v2.WordSetWordsReply.prototype.addWords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.WordSet.v2.WordSetWord, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.WordSet.v2.WordSetWordsReply} returns this
 */
proto.WordSet.v2.WordSetWordsReply.prototype.clearWordsList = function() {
  return this.setWordsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WordSet.v2.WordSetWord.prototype.toObject = function(opt_includeInstance) {
  return proto.WordSet.v2.WordSetWord.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WordSet.v2.WordSetWord} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WordSet.v2.WordSetWord.toObject = function(includeInstance, msg) {
  var f, obj = {
    wordpairid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    hasadded: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    wordforeign: jspb.Message.getFieldWithDefault(msg, 3, ""),
    wordnative: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WordSet.v2.WordSetWord}
 */
proto.WordSet.v2.WordSetWord.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WordSet.v2.WordSetWord;
  return proto.WordSet.v2.WordSetWord.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WordSet.v2.WordSetWord} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WordSet.v2.WordSetWord}
 */
proto.WordSet.v2.WordSetWord.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWordpairid(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasadded(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWordforeign(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setWordnative(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WordSet.v2.WordSetWord.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WordSet.v2.WordSetWord.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WordSet.v2.WordSetWord} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WordSet.v2.WordSetWord.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWordpairid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getHasadded();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getWordforeign();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getWordnative();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional int32 WordPairId = 1;
 * @return {number}
 */
proto.WordSet.v2.WordSetWord.prototype.getWordpairid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.WordSet.v2.WordSetWord} returns this
 */
proto.WordSet.v2.WordSetWord.prototype.setWordpairid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool HasAdded = 2;
 * @return {boolean}
 */
proto.WordSet.v2.WordSetWord.prototype.getHasadded = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.WordSet.v2.WordSetWord} returns this
 */
proto.WordSet.v2.WordSetWord.prototype.setHasadded = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string WordForeign = 3;
 * @return {string}
 */
proto.WordSet.v2.WordSetWord.prototype.getWordforeign = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.WordSet.v2.WordSetWord} returns this
 */
proto.WordSet.v2.WordSetWord.prototype.setWordforeign = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string WordNative = 4;
 * @return {string}
 */
proto.WordSet.v2.WordSetWord.prototype.getWordnative = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.WordSet.v2.WordSetWord} returns this
 */
proto.WordSet.v2.WordSetWord.prototype.setWordnative = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.WordSet.v2);
